import { type Participant, type User, type Subcategory } from "./types"

export const MOCK_USERS: User[] = [
  {
    id: "1",
    name: "Administrador PEA",
    email: "adminpea@turismoyculturas.gob.bo",
    password: "admin123",
    role: "admin",
  },
  {
    id: "2",
    name: "Maria Elena Gutierrez",
    email: "jurado1@premioeduardoabaroa.bo",
    password: "jurado123",
    role: "jury",
    assignedCategories: ["Artes Visuales", "Musica"],
  },
  {
    id: "3",
    name: "Carlos Mendoza",
    email: "jurado2@premioeduardoabaroa.bo",
    password: "jurado123",
    role: "jury",
    assignedCategories: ["Literatura", "Artes Escenicas"],
  },
  {
    id: "4",
    name: "Laura Paz Soldan",
    email: "coordinador@premioeduardoabaroa.bo",
    password: "coord123",
    role: "coordinator",
  },
]

export const MOCK_SUBCATEGORIES: Subcategory[] = [
  { id: "pintura", name: "Pintura", fileType: "image", categoryId: "artes-visuales" },
  { id: "escultura", name: "Escultura", fileType: "image", categoryId: "artes-visuales" },
  { id: "grabado", name: "Grabado", fileType: "image", categoryId: "artes-visuales" },
  { id: "fotografia", name: "Fotografia", fileType: "image", categoryId: "artes-visuales" },
  { id: "instalacion", name: "Instalacion", fileType: "image", categoryId: "artes-visuales" },
  { id: "arte-digital", name: "Arte Digital", fileType: "image", categoryId: "artes-visuales" },
  { id: "composicion-clasica", name: "Composicion Clasica", fileType: "audio", categoryId: "musica" },
  { id: "composicion-popular", name: "Composicion Popular", fileType: "audio", categoryId: "musica" },
  { id: "interpretacion-instrumental", name: "Interpretacion Instrumental", fileType: "audio", categoryId: "musica" },
  { id: "interpretacion-vocal", name: "Interpretacion Vocal", fileType: "audio", categoryId: "musica" },
  { id: "novela", name: "Novela", fileType: "document", categoryId: "literatura" },
  { id: "cuento", name: "Cuento", fileType: "document", categoryId: "literatura" },
  { id: "poesia", name: "Poesia", fileType: "document", categoryId: "literatura" },
  { id: "ensayo", name: "Ensayo", fileType: "document", categoryId: "literatura" },
  { id: "cronica", name: "Cronica", fileType: "document", categoryId: "literatura" },
  { id: "teatro", name: "Teatro", fileType: "link", categoryId: "artes-escenicas" },
  { id: "danza", name: "Danza", fileType: "link", categoryId: "artes-escenicas" },
  { id: "performance", name: "Performance", fileType: "link", categoryId: "artes-escenicas" },
  { id: "largometraje", name: "Largometraje", fileType: "link", categoryId: "cine-audiovisual" },
  { id: "cortometraje", name: "Cortometraje", fileType: "link", categoryId: "cine-audiovisual" },
  { id: "documental", name: "Documental", fileType: "link", categoryId: "cine-audiovisual" },
  { id: "animacion", name: "Animacion", fileType: "link", categoryId: "cine-audiovisual" },
]

export const MOCK_PARTICIPANTS: Participant[] = [
  {
    id: "1",
    name: "Ana Lucia Fernandez",
    workTitle: "Reflejos del Altiplano",
    year: 2025,
    category: "Artes Visuales",
    subcategory: "Pintura",
    modality: "Profesional",
    status: "public",
    thumbnail: "/placeholder-art.jpg",
    images: ["/placeholder-art.jpg"],
    createdAt: "2025-03-15",
  },
  {
    id: "2",
    name: "Roberto Mamani",
    workTitle: "Sonidos de la Tierra",
    year: 2025,
    category: "Musica",
    subcategory: "Composicion Popular",
    modality: "Profesional",
    status: "anonymous",
    audioUrl: "/placeholder-audio.mp3",
    createdAt: "2025-04-02",
  },
  {
    id: "3",
    name: "Patricia Quispe",
    workTitle: "Voces del Silencio",
    year: 2025,
    category: "Literatura",
    subcategory: "Poesia",
    modality: "Emergente",
    status: "private",
    createdAt: "2025-04-10",
  },
  {
    id: "4",
    name: "Diego Torrez",
    workTitle: "El Ultimo Carnaval",
    year: 2025,
    category: "Cine y Audiovisual",
    subcategory: "Cortometraje",
    modality: "Profesional",
    status: "public",
    videoUrl: "/placeholder-video.mp4",
    thumbnail: "/placeholder-film.jpg",
    createdAt: "2025-05-01",
  },
  {
    id: "5",
    name: "Susana Villca",
    workTitle: "Metamorfosis Andina",
    year: 2025,
    category: "Artes Escenicas",
    subcategory: "Danza",
    modality: "Profesional",
    status: "anonymous",
    thumbnail: "/placeholder-dance.jpg",
    createdAt: "2025-05-15",
  },
  {
    id: "6",
    name: "Jorge Colque",
    workTitle: "Fragmentos de Memoria",
    year: 2024,
    category: "Artes Visuales",
    subcategory: "Fotografia",
    modality: "Emergente",
    status: "public",
    images: ["/placeholder-photo.jpg"],
    createdAt: "2024-06-20",
  },
  {
    id: "7",
    name: "Carmen Rojas",
    workTitle: "La Sombra del Condor",
    year: 2024,
    category: "Literatura",
    subcategory: "Novela",
    modality: "Profesional",
    status: "private",
    createdAt: "2024-07-05",
  },
  {
    id: "8",
    name: "Martin Choque",
    workTitle: "Sincronia Ancestral",
    year: 2026,
    category: "Musica",
    subcategory: "Composicion Clasica",
    modality: "Profesional",
    status: "public",
    audioUrl: "/placeholder-audio.mp3",
    createdAt: "2026-01-10",
  },
  {
    id: "9",
    name: "Elena Gutierrez",
    workTitle: "Raices Urbanas",
    year: 2026,
    category: "Artes Visuales",
    subcategory: "Instalacion",
    modality: "Emergente",
    status: "public",
    thumbnail: "/placeholder-installation.jpg",
    images: ["/placeholder-installation.jpg"],
    createdAt: "2026-02-01",
  },
  {
    id: "10",
    name: "Oscar Alanoca",
    workTitle: "Tiempos Circulares",
    year: 2026,
    category: "Cine y Audiovisual",
    subcategory: "Documental",
    modality: "Profesional",
    status: "private",
    videoUrl: "/placeholder-video.mp4",
    thumbnail: "/placeholder-doc.jpg",
    createdAt: "2026-02-15",
  },
]
